name: mlflow_demo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.5
  - ipython
  - jupyter
  - numpy=1.16
  - pandas=0.23
  - scikit-learn=0.21
  - seaborn=0.9
  - matplotlib=3.1
  - mlflow=1.6